name = "StarFox"
author = "OrzMiku"
version = "1.0.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2af2e5ec5a79c40aaf422ba69f8167d09f00bac0895b9bc24fdc519082b8fd9d"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
