name = "StarFox"
author = "OrzMiku"
version = "1.1.1-hotfix+mc1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccb53f0c8503804b4d1653e67c3c1a49a6927424cfc1bb378ebca2c0a5e82421"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
