name = "StarFox"
author = "OrzMiku"
version = "1.0.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a79db124a3a0e92698fd5ab12d49d1e607a3ef0527a9556b1f5fe6b5ad4553e"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
