name = "StarFox"
author = "OrzMiku"
version = "1.1.1+mc1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05b584ac129b841effee7f7a5da3d2655855dc1739d05e0d8a5d565eb4b87728"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
