name = "StarFox"
author = "OrzMiku"
version = "1.1.1+mc1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f31b744e3da342d8a57b17ebb6f12313d5aa94342d3252eface7c16a4de04ce"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
