name = "StarFox"
author = "OrzMiku"
version = "1.0.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b142c76d1475eb12d9939b3040ebbf4b074a0b1564a4c7b959a6bcd2709e2544"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
