name = "StarFox"
author = "OrzMiku"
version = "1.1.1+mc1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba7ab422a9350f222a13b60ff7099ed5d044d9790d3394b77b45c1a3d3c9c9e5"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
