name = "StarFox"
author = "OrzMiku"
version = "1.1.1+mc1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3904951d3254f882167f0211bfb0100444ced12cf1e648fde2daa768047b5b97"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
