name = "StarFox"
author = "OrzMiku"
version = "1.1.1+mc1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fac15133bcd2340275fbfb0aae08a8901c76139e7fb6f1dea0a406335b602bd3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
