name = "StarFox"
author = "OrzMiku"
version = "1.1.1+mc1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "602a3a687d8a7c0ea6f16654c9360a6295c72a745ba2b65a9aa3f6de22010028"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
