name = "StarFox"
author = "OrzMiku"
version = "1.1.1+mc1.21.4.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "642216a5a9c5de83eea9d4078992973638645e8cd89068e1db675828efc0983e"

[versions]
minecraft = "1.21.4"
neoforge = "21.4.109-beta"
