name = "StarFox"
author = "OrzMiku"
version = "1.1.1+mc1.21.4.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40796ee8f694567b19eb2121dd8a3e91357f9c1d2445e9794856940f7f78561a"

[versions]
minecraft = "1.21.4"
neoforge = "21.4.109-beta"
