name = "StarFox"
author = "OrzMiku"
version = "1.0.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39cd9d4094351e8a05b44ac41771b835663c04bb47de59b640dec7475c38d7e6"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
