name = "StarFox"
author = "OrzMiku"
version = "1.1.1-hotfix+mc1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c60b9df0aa525b9253d768a6f06137889c8be22a96fdac19a7a7730d9b21509"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
