name = "StarFox"
author = "OrzMiku"
version = "1.0.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3b0470d88f1c57fcb41f24c7bd590ac1bdbeafd06e2628e085352c0264f6349"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
