name = "StarFox"
author = "OrzMiku"
version = "1.1.1+mc1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e2d40f1d47e5fdb91b3e6134642c44d56edce3f9f7b2249cf3327aa0ca7859d"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
