name = "StarFox"
author = "OrzMiku"
version = "1.0.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fdab00ca625f23310d7f7e9bf208826679d43b14ff4f84dfcaf8b061f9f8c1f"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
